version: '2'

services:
  database:
    image: mysql:5.7
    hostname: prod_server_mysql
    environment: 
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - NODE_ENV=production
      - HOSTNAME=prod
    networks: 
      - backend
  wordpress:
    image: wordpress:4.9.8
    hostname: prod_server_wordpress
    depends_on: 
      - database
    environment: 
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=password
      - NODE_ENV=production
      - HOSTNAME=prod
    networks: 
      - backend
      - frontend
  nginx:
    image: nginx:1.15
    hostname: prod_server_nginx
    depends_on: 
      - wordpress
    environment:
      - NODE_ENV=production
      - HOSTNAME=prod
    volumes:
      - /etc/ssl/private:/etc/ssl/certs
      - /var/www/html:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      #- ./default4.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
      - 443:443
#    command: nginx -t && service nginx start
    networks: 
      - frontend
    links:
      - fpm

  fpm:
    image: php:fpm
    hostname: prod_server_fpm
    environment:
      - NODE_ENV=production
      - HOSTNAME=prod
    volumes:
      - /var/www/html:/var/www/html
      - ./php-fpm.conf:/etc/php/7.2/fpm/php-fpm.conf
    networks:
      - frontend
networks:
  backend:
  frontend:
